### ISSUE TITLE
phone grinds to a halt after use

### ISSUE THREAD

**Issue by StevanWhite** [maxim-saplin/CrossPlatformDiskTest#10] opened 2020-05-15 17:57 UTC
Hi,

I'm just following up my review on Google Play, because this is a better forum for bug reports.

Again, this was on a Nokia 1 running Amazon 9.  The latest security updates are installed.  Also a lot of other apps are installed on the phone.

All I did was to run the storage tests (only, not the database tests).
I did not adjust any other settings.

After the tests finished, the phone ground almost to a halt.  App wouldn't respond, couldn't switch out of the app.  Finally the power button responded, said "System UI isn't responding".  From there I was able to kill it.

I can say however, it seemed the info didn't fit in the 4.5" screen of this device, and I scrolled the screen just before I noticed that everything had gotten very very slow.  Maybe scrolling triggered the issue.

**Comment by maxim-saplin** [comment] 2020-05-20 15:31
Hi, unfortunately I can't reproduce the issue and don't have the device to do a hands on investigation. Will close it for the time being as I have not come across any scroll related issues reported by other users (if the up hangs, it typically happens during test).

**Closed by maxim-saplin** 2020-05-20 15:31 UTC
